import = ["~/.config/alacritty/themes/themes/gruvbox_dark.toml"]

[font]
size = 25

[font.normal]
family = "UbuntuMono Nerd Font Mono"
style = "Regular"

[window]
decorations = "Full"
startup_mode = "Windowed"

[window.padding]
x = 5
y = 5

