require("nvim-treesitter.configs").setup({
  auto_install = true,
  ensure_installed = {
    "lua",
    "vim",
    "vimdoc",
    "javascript",
    "typescript",
    "tsx",
    "go",
    "php",
    "css",
    "json",
    "yaml",
    "bash",
    "markdown",
    "html",
    "elixir",
  },
  highlight = { enable = true },
  indent = { enable = true },
})
