#!/usr/bin/env bash

if [[ $# -eq 1 ]]; then
  selected=$1
else
  selected=$(find ~/code/kleyn ~/code/personal ~/code/boot-dev -mindepth 1 -maxdepth 1 -type d | fzf)
fi

if [[ -z $selected ]]; then
  exit 0;
fi

if [[ ! -d $selected ]]; then
  echo "Error: $selected is not a directory"
  exit 1
fi

selected_name=$(basename "$selected" | tr . _ | tr - _)
tmux_running=$(pgrep tmux)

# Tmux running?
if [[ -z $tmux_running ]]; then
  tmux new-session -s "$selected_name" -c "$selected"
  exit 0
fi

# tmux running but not attached
if [[ -z $TMUX ]]; then
  tmux new-session -A -s "$selected_name" -c "$selected"
  exit 0
fi

if ! tmux has-session -t=$selected_name 2> /dev/null; then 
  tmux new-session -ds "$selected_name" -c "$selected"
fi

tmux switch-client -t $selected_name
