# force a reload of the config file
unbind r 
bind r source-file ~/.tmux.conf

# mouse
setw -g mouse on

# Change prefix
unbind C-b
bind C-a send-prefix

set-option -g default-terminal "xterm-256-color"
