# force a reload of the config file
unbind r 
bind r source-file ~/.tmux.conf

# mouse
setw -g mouse on

# Change prefix
unbind C-b
set-option -g prefix C-a
bind C-a send-prefix

# Splitting panes
bind | split-window -h
bind - split-window -v
unbind '"'
unbind %

# Counting from 1
set -g base-index 1
setw -g pane-base-index 2

## COLORSCHEME: Gruvbox
set-option -g status "on"
set -g status-interval 5

# default statusbar colors
set-option -g status-style fg='#ebdbb2',bg='#3a3735'

set-option -g mode-style fg='#ebdbb2',bg='#665c54'

# ---- Windows ----
# default window title colors
set-window-option -g window-status-style fg='#665c54',bg='#3a3735'

# default window with an activity alert
set-window-option -g window-status-activity-style fg='#ebdbb2',bg='#3c3836'

# active window title colors
set-window-option -g window-status-current-style fg='#83a598',bg='#3c3836'

# ---- Pane ----
# pane borders
set-option -g pane-border-style fg='#3c3836'
set-option -g pane-active-border-style fg='#458588'

# pane number display
set-option -g display-panes-active-colour '#458588'
set-option -g display-panes-colour '#fe8019'

# ---- Command ----
# message info
set-option -g message-style fg='#ebdbb2',bg='#3a3735'

# writing commands inactive
set-option -g message-command-style fg='#ebdbb2',bg='#3c3836'

# ---- Miscellaneous ----
# clock
set-window-option -g clock-mode-colour '#83a598'

# bell
set-window-option -g window-status-bell-style fg='#3a3735',bg='#cc241d'

# ---- Formatting ----
set-option -g status-left-style none
set -g status-left-length 60
set -g status-left '#[fg=#3a3735,bg=#458588,bold] #S #[fg=#458588,bg=#3c3836,nobold]#[fg=#3c3836,bg=#3a3735]'

set-option -g status-right-style none
set -g status-right-length 150
set -g status-right '#[fg=#3c3836,bg=#3a3735]#[fg=#ebdbb2,bg=#3c3836] %Y-%m-%d | %H:%M:%S #[fg=#d79921,bg=#3c3836]#[fg=#3a3735,bg=#d79921,bold] #h '

set -g window-status-format "#[fg=#665c54,bg=#3a3735] #I|#[fg=#665c54,bg=#3a3735]#W "
set -g window-status-current-format "#[fg=#3a3735,bg=#3c3836]#[fg=#83a598,bg=#3c3836] #I|#[fg=#83a598,bg=#3c3836,bold]#W #[fg=#3c3836,bg=#3a3735,nobold]"
